### ISSUE TITLE
Extend block format

### ISSUE THREAD

**Issue by petterarvidsson** [konstructs/server#32]
We want to have a new block format that supports at least:
- a number of block types
- Able to store a damage value
- Storage for light level

A proposal that supports exactly this (and nothing else) would be
- 2 byte block type (2^16 types)
- 11 bits damage (2048 "HP")
- 5 bits light (32 levels)

**Comment by petterarvidsson** [comment]
@nsg What do you think?

**Comment by petterarvidsson** [comment]
Ideas: Add 7 more block models to represent the 7 permutations of 4x4 blocks. Also add rotation values so that all blocks can be rotated.

**Comment by nsg** [comment]
We also needs to store the light value, 3 bit? and another 3 bit to set the minimum light value (it's a light source). Do we need/want colours?

**Comment by petterarvidsson** [comment]
I think 3 bit might be a bit boring, the longest gradient from complete light to total darkness will be only 8 blocks, maybe 4 bits or even 5? I'd rather have fever bits for the source, maybe only 2, representing the 2 MSB of the others. I don't think we need that many levels of the minimum light?

**Comment by nsg** [comment]
Sounds good, any yes, you are correct that we probably do not need that many light levels on the sources.

**Comment by delconis** [comment]
I propose separating concern. Lighting / Damage / (solid, fluid, gas and avoidable) maybe should be implemented as plugins and the scope of this issue should be to implement a generic method to save extra data to blocks. And then on other issues address there concerns as plugins. To keep separation from core / extensions.

I think doing it in this fashion will allow people to better implement this server to fit there needs. Like my game uses lighting via the block type. And have no direct need server side to know if a area is lit. I would likely remove that code / values as it's un-needed. While if it was a plugin it could still be package and implemented on the server. But would be easily disabled / removed.

**Comment by petterarvidsson** [comment]
@delconis Sorry for this delayed answer. We have been thinking a lot around separation of concern when building this game, and I fundamentally agree with your concern. To give some background why we want to keep a small piece of data directly available in the block is mainly based on performance. To render a scene the server needs to send a lot of blocks to the client. Basically, right now we are sending a sphere of 20 chunks in diameter to the client. Each chunk is 32 blocks in all dimension. This means (allowing the simplification of having a sphere half the volume of a cube) that:
``` 
blocks = ((32 * 20)^3) / 2 = 131072000
```
That is a lot of blocks. The main performance restriction on the server is actually the logistics of getting these blocks from the disk of the server (or memory) to the client. We had some experiments around this in the beginning of the implementation, and found that the only way to get this really working was to send to the client the already compressed data from the server. Basically, the server does not even look at the data when the client asks for chunk, it just sends it. This gave the performance required to get things playable. For me this led me to the conclusion that anything that is required to be available on a per block basis needs to be provided directly in the block format. I did have a look at some possible dynamic options, like TLV or google protocol buffers, but the conclusion is that, even adding a just a couple of bytes to each block, and the additional logic required to unpack them, will have very big impacts on performance.

So basically, I would like the block format to be easily extensible, but I am still failing a possible way forward in getting that working nicely. I would love to be proven wrong :-) (And I think I might be!)

Nevertheless, I do think we should really try to limit what we store in the block format to the bare minimum required, and really keep it to things that is really required. To have a world where some areas are deemed to be dark based on their surroundings, this will always have to be calculated by the server, since the client never has the full picture of what's going on in the world, but only a small (in terms of the whole world) sphere shaped slice of it. So for me, lightning would be one of these few things that I would really want to keep in the block format. Also the basic properties of the block when it comes to collision avoidance (solid/gas/fluid/avoidable). The HP field might be more questionable, maybe here one could use the existing meta format for blocks that we use for inventories and make this a plugin.

**Comment by nsg** [comment]
@petterarvidsson what do you think about this issue, should we close it? Most things are implemented, the only really missing thing is the block shape ... will the model loading idea make this redundant?

**Comment by petterarvidsson** [comment]
Let's close it.
